import { z } from 'zod';

export const brandAssetCategorySchema = z.enum([
  'symbol',
  'lockup',
  'stacked',
  'vector',
  'animation',
]);

export const brandAssetFormatSchema = z.enum(['webp', 'svg', 'mp4', 'webm']);

export const brandAssetSchema = z.object({
  id: z.string(),
  name: z.string(),
  category: brandAssetCategorySchema,
  format: brandAssetFormatSchema,
  url: z.string(),
  fallbackUrl: z.string().optional(),
  webmUrl: z.string().optional(),
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  aspectRatio: z.enum(['1:1', '16:9', '9:16', 'custom']),
  alt: z.string(),
  description: z.string(),
  recommendedUse: z.string(),
});

export type BrandAssetCategory = z.infer<typeof brandAssetCategorySchema>;
export type BrandAssetFormat = z.infer<typeof brandAssetFormatSchema>;
export type BrandAsset = z.infer<typeof brandAssetSchema>;

/**
 * Catálogo Canónico Oficial de Recursos de Identidad Visual INDI 2026
 * Todos los activos están optimizados con WebP First y compresión >98%
 */
export const BRAND_ASSETS: Record<string, BrandAsset> = {
  alienSymbolSm: {
    id: 'alien-symbol-sm',
    name: 'Isotipo Alien Futurista (Compacto)',
    category: 'symbol',
    format: 'webp',
    url: '/brand/indi-alien-symbol-sm.webp',
    width: 128,
    height: 128,
    aspectRatio: '1:1',
    alt: 'Isotipo Oficial INDI 2026',
    description: 'Símbolo geométrico alienígena optimizado para micro-elementos, navbars y favicons.',
    recommendedUse: 'GlobalNavbar, MobileNavDrawer, AppEditorHeader, avatares y botones flotantes.',
  },
  alienSymbol: {
    id: 'alien-symbol',
    name: 'Isotipo Alien Futurista (Alta Definición)',
    category: 'symbol',
    format: 'webp',
    url: '/brand/indi-alien-symbol.webp',
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    alt: 'Isotipo Oficial INDI 2026 en Alta Resolución',
    description: 'Versión nítida para modales, vitrinas de producto y tarjetas Bento.',
    recommendedUse: 'Sección Hero, perfil público, modales de autenticación y vitrinas.',
  },
  techLockupSm: {
    id: 'tech-lockup-sm',
    name: 'Tech Brand Logo Lockup (Horizontal)',
    category: 'lockup',
    format: 'webp',
    url: '/brand/indi-tech-lockup-sm.webp',
    width: 688,
    height: 384,
    aspectRatio: '16:9',
    alt: 'Logotipo Horizontal INDI Identity Edge',
    description: 'Lockup horizontal con tipografía tech y símbolo integrado.',
    recommendedUse: 'Footers, cabeceras expandidas y credenciales de producto.',
  },
  techLockup: {
    id: 'tech-lockup',
    name: 'Tech Brand Logo Lockup (Master 16:9)',
    category: 'lockup',
    format: 'webp',
    url: '/brand/indi-tech-lockup.webp',
    width: 1376,
    height: 768,
    aspectRatio: '16:9',
    alt: 'Logotipo Maestro INDI 2026 en 16:9',
    description: 'Composición panorámica para banners principales, presentaciones y Open Graph.',
    recommendedUse: 'Portadas, diapositivas de presentaciones y banners corporativos.',
  },
  stackedHero: {
    id: 'stacked-hero',
    name: 'Brand Logo Stacked (Vertical 9:16)',
    category: 'stacked',
    format: 'webp',
    url: '/brand/indi-stacked-hero.webp',
    width: 768,
    height: 1376,
    aspectRatio: '9:16',
    alt: 'Composición Vertical INDI para Móvil',
    description: 'Diseño vertical de alto impacto para dispositivos móviles y stories.',
    recommendedUse: 'Previsualización móvil, stories y pantallas verticales.',
  },
  vectorMark: {
    id: 'vector-mark',
    name: 'Vector Alien Head Logo Mark',
    category: 'vector',
    format: 'webp',
    url: '/brand/indi-vector-mark.webp',
    width: 800,
    height: 800,
    aspectRatio: '1:1',
    alt: 'Trazo Vectorial de la Cabeza Alienígena',
    description: 'Símbolo vectorial limpio sobre fondo oscuro para badges e insignias.',
    recommendedUse: 'Insignias de verificación, marcas de agua y fondos sutiles.',
  },
  vectorLight: {
    id: 'vector-light',
    name: 'Vector Design (Contraste Claro)',
    category: 'vector',
    format: 'webp',
    url: '/brand/indi-vector-light.webp',
    width: 1376,
    height: 768,
    aspectRatio: '16:9',
    alt: 'Identidad Visual INDI sobre Fondo Claro',
    description: 'Variante de contraste alto para impresión, documentos claros y reportes PDF.',
    recommendedUse: 'Exportación a PDF A4, membretes y modo claro.',
  },
  brandRevealVideo: {
    id: 'brand-reveal-video',
    name: 'Brand Animation Reveal 1080p',
    category: 'animation',
    format: 'mp4',
    url: '/brand/indi-brand-reveal.mp4',
    width: 1920,
    height: 1080,
    aspectRatio: '16:9',
    alt: 'Animación Oficial de la Marca INDI',
    description: 'Video revelación con efectos de iluminación y aura cinemática.',
    recommendedUse: 'Hero interactivo, modal de bienvenida y vitrina de identidad.',
  },
  isotipoSvg: {
    id: 'isotipo-svg',
    name: 'Isotipo Vectorial Puro (SVG Transparente)',
    category: 'symbol',
    format: 'svg',
    url: '/brand/indi-isotipo-transparent.svg',
    width: 512,
    height: 512,
    aspectRatio: '1:1',
    alt: 'Isotipo INDI SVG Vectorial',
    description: 'Gráfico vectorial escalable con gradientes prismáticos y resplandor radial.',
    recommendedUse: 'Renderizado en cliente con CSS dinámico y máxima nitidez vectorial.',
  },
  logoHorizontalSvg: {
    id: 'logo-horizontal-svg',
    name: 'Logotipo Horizontal Vectorial (SVG Transparente)',
    category: 'lockup',
    format: 'svg',
    url: '/brand/indi-logo-horizontal-transparent.svg',
    width: 800,
    height: 240,
    aspectRatio: 'custom',
    alt: 'Logotipo Horizontal INDI SVG Vectorial',
    description: 'Logotipo completo con isotipo y lema IDENTITY EDGE en vector puro.',
    recommendedUse: 'Cabeceras web premium y presentaciones de alta resolución.',
  },
  logoAnimated: {
    id: 'logo-animated',
    name: 'Logotipo Animado Viviente (1:1 Loop Ultra-Ligero)',
    category: 'animation',
    format: 'mp4',
    url: '/brand/indi-logo-animated.mp4',
    webmUrl: '/brand/indi-logo-animated.webm',
    fallbackUrl: '/brand/indi-alien-symbol-sm.webp',
    width: 320,
    height: 320,
    aspectRatio: '1:1',
    alt: 'Logotipo Animado Oficial INDI 2026',
    description: 'Animación en bucle suave y optimizada (<66 KB) para navbars, cabeceras y logotipos vivientes.',
    recommendedUse: 'Logotipo principal en GlobalNavbar, headers y badges.',
  },
  logoWideAnimated: {
    id: 'logo-wide-animated',
    name: 'Logotipo Panorámico Animado (16:9 Loop)',
    category: 'animation',
    format: 'mp4',
    url: '/brand/indi-logo-wide-animated.mp4',
    fallbackUrl: '/brand/indi-tech-lockup.webp',
    width: 640,
    height: 360,
    aspectRatio: '16:9',
    alt: 'Logotipo Panorámico Animado Oficial INDI',
    description: 'Animación panorámica ligera (<70 KB) para vitrinas y cabeceras horizontales.',
    recommendedUse: 'Hero, presentaciones y banners animados.',
  },
};

